### ISSUE TITLE
Error when installing the jlab extension

### ISSUE THREAD

**Issue by martinRenou** [vidartf/ipyscales#16]
I get a ModuleNotFoundError when installing the jlab extension
```
ModuleNotFoundError: Module not found: Error: Can't resolve '../styles/plugin.css' in '/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/lib'
    at factory.create (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:535:10)
    at factory (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:397:22)
    at resolver (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
    at asyncLib.parallel (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
    at /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/neo-async/async.js:2830:7
    at /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/neo-async/async.js:6877:13
    at normalResolver.resolve (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
    at doResolve (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:184:12)
    at hook.callAsync (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at resolver.doResolve (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:37:5)
    at hook.callAsync (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at hook.callAsync (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn42 (eval at create (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at resolver.doResolve (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:42:38)
    at hook.callAsync (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn1 (eval at create (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at hook.callAsync (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/Resolver.js:238:5)
    at _fn0 (eval at create (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at fs.stat (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:22:13)
    at process.nextTick (/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:73:15)
    at processTicksAndRejections (internal/process/task_queues.js:79:9)
resolve '../styles/plugin.css' in '/home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/lib'
  using description file: /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/package.json (relative path: ./styles/plugin.css)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/styles/plugin.css doesn't exist
      .wasm
        Field 'browser' doesn't contain a valid alias configuration
        /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/styles/plugin.css.wasm doesn't exist
      .mjs
        Field 'browser' doesn't contain a valid alias configuration
        /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/styles/plugin.css.mjs doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/styles/plugin.css.js doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/styles/plugin.css.json doesn't exist
      as directory
        /home/martin/miniconda3/envs/geopython/share/jupyter/lab/staging/node_modules/jupyter-scales/styles/plugin.css doesn't exist
error Command failed with exit code 1.
```

**Comment by vidartf** [comment]
Thanks, fixed proposed in #17.

**Comment by jhgoebbert** [comment]
I can confirm, that this issue is present in version 0.4.0, which is the latest available through pip.

**Comment by bsyouness** [comment]
I'm still running into this issue. Is there a fix? @vidartf @martinRenou (Salut Martin! 😄)

**Comment by martinRenou** [comment]
Salut @bsyouness ! I hope you are doing well :)

You can try applying this fix locally: https://github.com/vidartf/ipyscales/pull/17 but I am not entirely sure that would make it work.

Also be sure to install `nodejs=12` at least, `conda` has a bug that makes it install `nodejs=6` which is too old for building labextensions. You can also try mamba which does not have this `nodejs` issue ;)
